# Generated by Django 5.0.4 on 2024-04-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.TextField()),
                ('code', models.CharField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Party',
        ),
    ]
