# Generated by Django 5.0.4 on 2024-04-28 18:27

import coupapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupapp', '0003_room_playing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='members',
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('sid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('room', models.ForeignKey(on_delete=models.SET(coupapp.models.get_default_room), to='coupapp.room')),
            ],
        ),
    ]
