# Generated by Django 5.0.4 on 2024-04-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupapp', '0004_remove_room_id_remove_room_members_alter_room_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cards',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='player',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
